

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/wechat_shop?characterEncoding=utf-8&useSSL=false& serverTimezone=UTC
  jpa:
    show-sql: true
